# version: "3.8"

services:
  app:
    build:
      context: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - logs
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/app_db
      - LOG_SERVER_HOST=logs
      - LOG_SERVER_PORT=24224

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    volumes:
      - db_data:/var/lib/postgresql/data  # Persistencia de datos
      - ./db:/docker-entrypoint-initdb.d # Scripts de inicialización
    ports:
      - "5432:5432"  

  logs:
    build:
      context: ./logs
    ports:
      - "24224:24224"
    volumes:
      - ./logs/output:/fluentd/log

  tests:
    build:
      context: ./tests
    depends_on:
      - app
      - db
      - logs
    network_mode: "service:app"

volumes:
  db_data:
